repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-xmllint
    rev: master
    hooks:
      - id: xmllint
        args: [--format]
        files: \.(xml|config)$
